package com.bloomtechspringbootgp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

//This was generated by Spring Initializer
// DO NOT CHANGE THIS CODE
@SpringBootApplication //Tells server this is a Spring Boot App
public class FirstSpringBootAppApplication {

	public static void main(String[] args) {
		//start the server with this class
		SpringApplication.run(FirstSpringBootAppApplication.class, args);
	}

}
